# Generated by Django 4.1.4 on 2022-12-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeTyp', models.CharField(max_length=100)),
                ('nomTyp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeClass', models.CharField(max_length=100)),
                ('nomClass', models.CharField(max_length=100)),
                ('typClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.type')),
            ],
        ),
    ]
