# Generated by Django 4.1.4 on 2022-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='descrpClass',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
