# Generated by Django 4.1.4 on 2023-01-01 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0003_classe_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProf', models.CharField(max_length=300)),
                ('MatriculeProf', models.CharField(max_length=200)),
                ('TéléphoneProf', models.CharField(max_length=20)),
                ('EmailProf', models.CharField(max_length=100)),
                ('photoProf', models.ImageField(upload_to='photosProfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMat', models.CharField(max_length=300)),
                ('CodeMat', models.CharField(max_length=200)),
                ('ClassMat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.classe')),
                ('ProfMat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.professeur')),
            ],
        ),
    ]
