# Generated by Django 4.1.4 on 2023-01-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0004_professeur_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professeur',
            old_name='TéléphoneProf',
            new_name='TelephoneProf',
        ),
        migrations.AddField(
            model_name='matiere',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professeur',
            name='prenomProf',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
