# Generated by Django 4.1.4 on 2023-01-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0005_rename_téléphoneprof_professeur_telephoneprof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='ClassMat',
        ),
        migrations.AddField(
            model_name='matiere',
            name='ClassMat',
            field=models.ManyToManyField(to='SCOOLAPP.classe'),
        ),
    ]
