# Generated by Django 4.1.4 on 2023-01-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0006_remove_matiere_classmat_matiere_classmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatriculeElev', models.CharField(max_length=200)),
                ('nomElev', models.CharField(max_length=300)),
                ('prenomElev', models.CharField(max_length=300)),
                ('TelephoneElev', models.CharField(max_length=20)),
                ('photoElev', models.ImageField(upload_to='photosEleves/')),
                ('state', models.BooleanField(default=False)),
                ('ClassElev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.classe')),
            ],
        ),
    ]
