# Generated by Django 4.1.4 on 2023-01-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0008_alter_eleve_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nomClass']},
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={'ordering': ['nomElev', 'prenomElev']},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nomMat']},
        ),
        migrations.AlterModelOptions(
            name='professeur',
            options={'ordering': ['nomProf', 'prenomProf']},
        ),
    ]
